// Generated by https://quicktype.io

export interface Ayahs {
    verses: Ayah[];
    meta:   Meta;
}

export interface Meta {
    current_page: number;
    next_page:    null;
    prev_page:    null;
    total_pages:  number;
    total_count:  number;
}

export interface Ayah {
    id:             number;
    verse_number:   number;
    chapter_id:     number;
    verse_key:      string;
    text_madani:    string;
    text_indopak:   string;
    text_simple:    string;
    juz_number:     number;
    hizb_number:    number;
    rub_number:     number;
    sajdah:         null;
    sajdah_number:  null;
    page_number:    number;
    media_contents: MediaContent[];
    words:          Word[];
}

export interface MediaContent {
    url:         string;
    embed_text:  string;
    provider:    string;
    author_name: string;
}

export interface Word {
    id:              number;
    position:        number;
    text_madani:     null | string;
    text_indopak:    null;
    text_simple:     null | string;
    verse_key:       string;
    class_name:      ClassName;
    line_number:     number;
    page_number:     number;
    code:            string;
    code_v3:         string;
    char_type:       CharType;
    audio:           Audio;
    translation:     Translation | null;
    transliteration: Translation | null;
}

export interface Audio {
    url: null | string;
}

export enum CharType {
    End = "end",
    Word = "word",
}

export enum ClassName {
    P1 = "p1",
}

export interface Translation {
    id:            number;
    language_name: LanguageName;
    text:          string;
    resource_name: ResourceName | null;
    resource_id:   number;
}

export enum LanguageName {
    English = "english",
    Indonesian = "indonesian",
}

export enum ResourceName {
    IndonesianWordByWordTranslation = "Indonesian word by word translation",
}
