// Generated by https://quicktype.io

export interface Juzs {
    juzs: Juz[];
}

export interface Juz {
    id:            number;
    juz_number:    number;
    verse_mapping: { [key: string]: string };
}
